"""
PR&DW Grievance Portal — One-Click Runner
==========================================
Run this script to set up and launch the demo application.
    python runner.py

What it does:
  1. Installs Python dependencies (if needed)
  2. Checks / creates the .env configuration file
  3. Verifies MongoDB connectivity
  4. Seeds the database with demo users and grievances
  5. Starts the web server at http://localhost:8000

Requirements:
  - Python 3.10+
  - MongoDB running locally (default: mongodb://localhost:27017)
  - An OpenAI API key (for the chatbot and AI features)
"""

import os
import sys
import subprocess
import secrets
import uuid
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
ENV_PATH = SCRIPT_DIR / ".env"

# ── Colours for terminal output ──────────────────────────────────────────────
GREEN = "\033[92m"
YELLOW = "\033[93m"
RED = "\033[91m"
CYAN = "\033[96m"
BOLD = "\033[1m"
RESET = "\033[0m"


def banner():
    print(f"""
{CYAN}{BOLD}╔══════════════════════════════════════════════════════════╗
║   PR&DW Grievance Portal — One-Click Runner              ║
╚══════════════════════════════════════════════════════════╝{RESET}
""")


def step(n, total, msg):
    print(f"\n{BOLD}[{n}/{total}]{RESET} {msg}")


# ── Step 1: Install dependencies ─────────────────────────────────────────────
def install_dependencies():
    step(1, 5, "Checking Python dependencies...")
    req_file = SCRIPT_DIR / "requirements.txt"
    if not req_file.exists():
        print(f"  {RED}requirements.txt not found in {SCRIPT_DIR}{RESET}")
        sys.exit(1)

    try:
        import fastapi, pymongo, openai, dotenv, jose, passlib, jinja2
        print(f"  {GREEN}All core packages already installed.{RESET}")
    except ImportError:
        print(f"  Installing from requirements.txt...")
        subprocess.check_call(
            [sys.executable, "-m", "pip", "install", "-r", str(req_file), "-q"],
            stdout=subprocess.DEVNULL if os.name == "nt" else None,
        )
        print(f"  {GREEN}Dependencies installed.{RESET}")


# ── Step 2: Check / create .env ──────────────────────────────────────────────
def setup_env():
    step(2, 5, "Checking environment configuration...")

    if ENV_PATH.exists():
        from dotenv import load_dotenv
        load_dotenv(ENV_PATH, override=True)
        missing = []
        if not os.getenv("OPENAI_API_KEY"):
            missing.append("OPENAI_API_KEY")
        if not os.getenv("JWT_SECRET") or len(os.getenv("JWT_SECRET", "")) < 32:
            missing.append("JWT_SECRET")
        if not missing:
            print(f"  {GREEN}.env file found and valid.{RESET}")
            return
        print(f"  {YELLOW}.env file exists but missing: {', '.join(missing)}{RESET}")
    else:
        print(f"  {YELLOW}No .env file found. Creating one...{RESET}")

    env_values = {}

    # OpenAI API Key
    current_key = os.getenv("OPENAI_API_KEY", "")
    if current_key and current_key.startswith("sk-"):
        env_values["OPENAI_API_KEY"] = current_key
    else:
        print(f"\n  {BOLD}OpenAI API Key{RESET}")
        print(f"  Get yours at: https://platform.openai.com/api-keys")
        key = input(f"  Enter your OpenAI API key: ").strip()
        if not key:
            print(f"  {RED}OpenAI API key is required for AI features.{RESET}")
            sys.exit(1)
        env_values["OPENAI_API_KEY"] = key

    # MongoDB URL
    env_values["MONGODB_URL"] = os.getenv("MONGODB_URL", "mongodb://localhost:27017")

    # JWT Secret
    current_jwt = os.getenv("JWT_SECRET", "")
    if current_jwt and len(current_jwt) >= 32:
        env_values["JWT_SECRET"] = current_jwt
    else:
        env_values["JWT_SECRET"] = secrets.token_urlsafe(48)
        print(f"  {GREEN}Generated JWT secret automatically.{RESET}")

    # Model
    env_values["OPENAI_MODEL"] = os.getenv("OPENAI_MODEL", "gpt-4o-mini")
    env_values["EMBEDDING_MODEL"] = os.getenv("EMBEDDING_MODEL", "text-embedding-3-large")

    # Write .env
    lines = [
        f"# Auto-generated by runner.py",
        f"OPENAI_API_KEY={env_values['OPENAI_API_KEY']}",
        f"OPENAI_MODEL={env_values['OPENAI_MODEL']}",
        f"EMBEDDING_MODEL={env_values['EMBEDDING_MODEL']}",
        f"MONGODB_URL={env_values['MONGODB_URL']}",
        f"JWT_SECRET={env_values['JWT_SECRET']}",
        f"# Qdrant is optional — leave blank to run without knowledge base",
        f"QDRANT_URL=",
        f"QDRANT_API_KEY=",
    ]
    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")

    from dotenv import load_dotenv
    load_dotenv(ENV_PATH, override=True)
    print(f"  {GREEN}.env file created at {ENV_PATH}{RESET}")


# ── Step 3: Check MongoDB ────────────────────────────────────────────────────
def check_mongodb():
    step(3, 5, "Checking MongoDB connection...")
    from pymongo import MongoClient
    from pymongo.errors import ConnectionFailure, ServerSelectionTimeoutError

    url = os.getenv("MONGODB_URL", "mongodb://localhost:27017")
    try:
        client = MongoClient(url, serverSelectionTimeoutMS=5000)
        client.admin.command("ping")
        print(f"  {GREEN}MongoDB is running at {url}{RESET}")
        client.close()
    except (ConnectionFailure, ServerSelectionTimeoutError):
        print(f"  {RED}Cannot connect to MongoDB at {url}{RESET}")
        print(f"\n  {BOLD}MongoDB is required.{RESET} Please ensure it is running:")
        print(f"    • Local install:  mongod --dbpath /data/db")
        print(f"    • Docker:         docker run -d -p 27017:27017 --name mongo mongo:7")
        print(f"    • Or set MONGODB_URL in .env to point to your instance\n")
        sys.exit(1)


# ── Step 4: Seed database (MongoDB only, no Qdrant) ─────────────────────────
def seed_database():
    step(4, 5, "Seeding database with demo data...")
    from pymongo import MongoClient
    from passlib.context import CryptContext
    from datetime import datetime, timedelta, timezone

    url = os.getenv("MONGODB_URL", "mongodb://localhost:27017")
    client = MongoClient(url)
    db = client.grievance_system
    pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

    # Check if already seeded
    existing_users = db.users.count_documents({})
    if existing_users > 0:
        print(f"  {YELLOW}Database already has {existing_users} users. Skipping seed.{RESET}")
        print(f"  (Delete the 'grievance_system' database to re-seed)")
        client.close()
        return

    # ── Users ──
    USERS = [
        {"username": "citizen1", "password": "citizen123", "full_name": "Rajesh Kumar Swain",
         "email": "rajesh.swain@email.com", "phone": "9876543210", "role": "citizen", "department": None},
        {"username": "officer1", "password": "officer123", "full_name": "Smt. Priya Pattnaik, BDO",
         "email": "priya.bdo@panchayat.odisha.gov.in", "phone": "9988776655", "role": "officer", "department": "panchayati_raj"},
        {"username": "admin", "password": "admin123", "full_name": "System Administrator",
         "email": "admin@panchayat.odisha.gov.in", "phone": None, "role": "admin", "department": None},
    ]

    for u in USERS:
        db.users.insert_one({
            "_id": str(uuid.uuid4()),
            "username": u["username"],
            "hashed_password": pwd_context.hash(u["password"]),
            "full_name": u["full_name"],
            "email": u["email"],
            "phone": u["phone"],
            "role": u["role"],
            "department": u["department"],
            "created_at": datetime.now(timezone.utc),
        })
        print(f"    Created user: {u['username']} ({u['role']})")
    db.users.create_index([("username", 1)], unique=True)

    # ── Grievances ──
    citizen1 = db.users.find_one({"username": "citizen1"})
    citizen1_id = str(citizen1["_id"]) if citizen1 else None

    officer_cats = {
        "panchayati_raj": "block_dev_officer",
        "rural_water_supply": "executive_engineer_rwss",
        "mgnregs": "mgnregs_programme_officer",
        "rural_housing": "block_dev_officer",
        "rural_livelihoods": "drda_project_director",
        "sanitation": "block_dev_officer",
        "infrastructure": "block_dev_officer",
        "general": "general_officer",
    }

    GRIEVANCES = [
        {"title": "How to check PMAY-G application status online",
         "description": "I want to know how to check my PMAY-G housing application status online.",
         "district": "Puri", "department": "rural_housing", "priority": "low",
         "sentiment": "neutral", "status": "resolved", "resolution_tier": "self_resolvable",
         "resolution_type": "ai",
         "ai_resolution": "You can check your PMAY-G application status online through the **Awaas+ portal**:\n\n1. Visit [awaassoft.nic.in](https://awaassoft.nic.in)\n2. Click on **'Stakeholders'** → **'IAY/PMAY-G Beneficiary'**\n3. Enter your **Registration Number** or search by name\n\nAlternatively, call the **PMAY-G helpline: 1800-11-6446** (toll-free).",
         "confidence_score": 0.92, "resolution_feedback": 5,
         "citizen_name": "Ganesh Behera", "citizen_email": "ganesh.behera@email.com"},
        {"title": "MGNREGS wages not paid for 60 days in Kalahandi",
         "description": "I and 30 other workers completed road construction work under MGNREGS 60 days ago. Wages have not been credited.",
         "district": "Kalahandi", "department": "mgnregs", "priority": "high",
         "sentiment": "frustrated", "status": "resolved", "resolution_tier": "officer_action",
         "resolution_type": "manual",
         "manual_resolution": "**Investigation completed.** FTO was stuck due to incorrect bank account details for 23 workers. Accounts corrected via Aadhaar re-verification. Wages transferred within 7 days. Delay compensation also credited.",
         "assigned_officer": "Smt. Priya Pattnaik, BDO", "resolution_feedback": 5,
         "notes": [{"officer": "Smt. Priya Pattnaik, BDO", "content": "All accounts corrected. FTO resubmitted.", "note_type": "citizen_facing"}],
         "citizen_name": "Laxman Naik", "citizen_email": "laxman.naik@email.com"},
        {"title": "Bore well non-functional for 4 months in tribal village",
         "description": "The only bore well in our tribal hamlet has not been working for 4 months. Women and children walk 3 km daily for water.",
         "district": "Mayurbhanj", "department": "rural_water_supply", "priority": "urgent",
         "sentiment": "frustrated", "status": "resolved", "resolution_tier": "officer_action",
         "resolution_type": "manual",
         "manual_resolution": "**RWSS JE inspection:** Submersible pump motor burned out. New 1.5 HP motor installed under Basudha budget within 5 days. Hand pump handle replaced. GP Jalasathi trained on maintenance.",
         "assigned_officer": "Smt. Priya Pattnaik, BDO", "resolution_feedback": 5,
         "citizen_name": "Gurubari Hansda", "citizen_email": "gurubari.hansda@email.com"},
        {"title": "Water from JJM tap is yellow and smells bad",
         "description": "Water from JJM taps in our village in Dhenkanal is yellowish with a metallic smell. Children have been getting stomach problems.",
         "district": "Dhenkanal", "department": "rural_water_supply", "priority": "urgent",
         "sentiment": "frustrated", "status": "resolved", "resolution_tier": "officer_action",
         "resolution_type": "manual",
         "manual_resolution": "**Water quality test confirmed high iron (3.2 mg/L vs 0.3 mg/L safe limit).** Iron Removal Plant installed under JJM water quality component. Follow-up testing confirmed safe levels.",
         "assigned_officer": "Smt. Priya Pattnaik, BDO", "resolution_feedback": 5,
         "citizen_name": "Surekha Pradhan", "citizen_email": "surekha.pradhan@email.com"},
        {"title": "No JJM tap water connection despite being in village action plan",
         "description": "Our habitation was included in the JJM Village Action Plan last year. Pipeline work started but stopped 2 months ago.",
         "district": "Koraput", "department": "rural_water_supply", "priority": "urgent",
         "sentiment": "frustrated", "status": "in_progress", "resolution_tier": "officer_action",
         "assigned_officer": "Smt. Priya Pattnaik, BDO",
         "notes": [{"officer": "Smt. Priya Pattnaik, BDO", "content": "RWSS EE contacted. Percussion drilling team being mobilized for rocky terrain. Expected completion: 4-6 weeks.", "note_type": "citizen_facing"}],
         "citizen_name": "Dambaru Majhi", "citizen_email": "dambaru.majhi@email.com"},
        {"title": "BGBO road project abandoned halfway in Rayagada block",
         "description": "A 3 km rural road sanctioned under BGBO has been abandoned after only 1 km. Contractor left 4 months ago.",
         "district": "Rayagada", "department": "infrastructure", "priority": "high",
         "sentiment": "frustrated", "status": "in_progress", "resolution_tier": "officer_action",
         "assigned_officer": "Smt. Priya Pattnaik, BDO",
         "notes": [{"officer": "Smt. Priya Pattnaik, BDO", "content": "Contract termination initiated. Re-tendering will begin shortly.", "note_type": "citizen_facing"}],
         "citizen_name": "Kamala Sabar", "citizen_email": "kamala.sabar@email.com"},
        {"title": "Finance Commission grant funds allegedly misused by Sarpanch",
         "description": "Sarpanch used Finance Commission untied grant money to construct a boundary wall around his own property.",
         "district": "Kendrapara", "department": "infrastructure", "priority": "high",
         "sentiment": "frustrated", "status": "escalated", "resolution_tier": "escalation",
         "citizen_name": None, "citizen_email": None, "is_anonymous": True},
        {"title": "Sarpanch demanding bribe for PMAY-G beneficiary selection",
         "description": "Sarpanch is demanding Rs. 10,000 from each family to include them in the PMAY-G beneficiary list.",
         "district": "Malkangiri", "department": "rural_housing", "priority": "urgent",
         "sentiment": "frustrated", "status": "escalated", "resolution_tier": "escalation",
         "citizen_name": None, "citizen_email": None, "is_anonymous": True},
        {"title": "PMAY-G second installment not released despite completing lintel",
         "description": "I completed lintel level for my PMAY-G house 3 months ago. Second installment of Rs. 40,000 has not been released.",
         "district": "Ganjam", "department": "rural_housing", "priority": "high",
         "sentiment": "frustrated", "status": "pending", "resolution_tier": "officer_action",
         "citizen_name": "Somanath Behera", "citizen_email": "somanath.behera@email.com"},
        {"title": "How to register complaint about non-functional street light",
         "description": "Solar street lights installed by GP stopped working 2 weeks ago. Where do I complain?",
         "district": "Cuttack", "department": "panchayati_raj", "priority": "low",
         "sentiment": "neutral", "status": "pending", "resolution_tier": "self_resolvable",
         "resolution_type": "ai",
         "ai_resolution": "For non-functional solar street lights:\n\n1. **Contact GP Secretary** or **Sarpanch** in writing\n2. Check if lights are under **5-year warranty** — manufacturer must repair at no cost\n3. If no action in 7 days, contact the **BDO**\n4. Report on **e-Gram Swaraj portal** (egramswaraj.gov.in)",
         "confidence_score": 0.88,
         "citizen_name": "Sudhir Mohanty", "citizen_email": "sudhir.mohanty@email.com"},
        {"title": "JJM pipeline laid but no water flowing for 2 months",
         "description": "JJM pipeline was laid and taps installed but no water has ever flowed. Overhead tank seems not connected.",
         "district": "Angul", "department": "rural_water_supply", "priority": "high",
         "sentiment": "negative", "status": "pending", "resolution_tier": "officer_action",
         "citizen_name": "Bijay Kumar Sahu", "citizen_email": "bijay.sahu@email.com"},
        {"title": "MGNREGS worksite has no shade or drinking water facility",
         "description": "No shade shelter, drinking water, or first-aid kit at MGNREGS worksite. Women workers suffering in heat.",
         "district": "Bargarh", "department": "mgnregs", "priority": "medium",
         "sentiment": "negative", "status": "pending", "resolution_tier": "officer_action",
         "citizen_name": "Pramila Sahu", "citizen_email": "pramila.sahu@email.com"},
    ]

    now = datetime.now(timezone.utc)
    priority_hours = {"low": 360, "medium": 168, "high": 72, "urgent": 24}

    for i, g in enumerate(GRIEVANCES):
        seq = db.counters.find_one_and_update(
            {"_id": "grievance"}, {"$inc": {"seq": 1}},
            upsert=True, return_document=True
        )
        tracking = f"GRV-{now.year}-{seq['seq']:06d}"
        is_anon = g.get("is_anonymous", False)
        status = g["status"]
        created = now - timedelta(days=25 - i)

        if status == "resolved":
            updated = created + timedelta(days=3, hours=i * 2)
        elif status in ("in_progress", "escalated"):
            updated = now - timedelta(days=1)
        else:
            updated = created + timedelta(hours=i)

        sla = now + timedelta(hours=priority_hours.get(g["priority"], 168))

        seed_notes = []
        for n in g.get("notes", []):
            seed_notes.append({
                "officer": n["officer"], "content": n["content"],
                "note_type": n["note_type"],
                "created_at": created + timedelta(days=1, hours=len(seed_notes) * 6),
            })

        db.grievances.insert_one({
            "_id": str(uuid.uuid4()), "tracking_number": tracking,
            "title": g["title"], "description": g["description"],
            "citizen_name": None if is_anon else g.get("citizen_name"),
            "citizen_email": None if is_anon else g.get("citizen_email"),
            "citizen_phone": None, "is_anonymous": is_anon,
            "language": "english", "district": g.get("district"),
            "department": g["department"], "priority": g["priority"],
            "officer_category": officer_cats.get(g["department"], "general_officer"),
            "status": status, "sentiment": g["sentiment"],
            "created_at": created, "updated_at": updated, "sla_deadline": sla,
            "ai_resolution": g.get("ai_resolution"),
            "manual_resolution": g.get("manual_resolution"),
            "resolution_tier": g.get("resolution_tier", "officer_action"),
            "resolution_type": g.get("resolution_type"),
            "confidence_score": g.get("confidence_score", 0.0),
            "assigned_officer": g.get("assigned_officer"),
            "resolution_feedback": g.get("resolution_feedback"),
            "notes": seed_notes, "location": None,
            "citizen_user_id": citizen1_id,
        })
        tag = {"resolved": "✅", "in_progress": "🔄", "escalated": "⚠️", "pending": "⏳"}.get(status, "")
        print(f"    {tag} {tracking}: {g['title'][:55]}...")

    db.grievances.create_index("created_at")
    db.grievances.create_index("status")
    db.grievances.create_index("department")
    db.grievances.create_index("priority")
    db.grievances.create_index("tracking_number")

    print(f"\n  {GREEN}Seeded {len(USERS)} users + {len(GRIEVANCES)} grievances.{RESET}")
    client.close()


# ── Step 5: Launch server ────────────────────────────────────────────────────
def launch_server():
    step(5, 5, "Starting the web server...")
    print(f"""
  {GREEN}{BOLD}Server starting!{RESET}

  {BOLD}Open in your browser:{RESET}  {CYAN}http://localhost:8000{RESET}

  {BOLD}Demo accounts:{RESET}
    Citizen:  {CYAN}citizen1{RESET} / {CYAN}citizen123{RESET}
    Officer:  {CYAN}officer1{RESET} / {CYAN}officer123{RESET}
    Admin:    {CYAN}admin{RESET}    / {CYAN}admin123{RESET}

  Press {BOLD}Ctrl+C{RESET} to stop the server.
""")
    import uvicorn
    os.chdir(str(SCRIPT_DIR))
    uvicorn.run("ticketer:app", host="0.0.0.0", port=8000, reload=False)


# ── Main ─────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    banner()
    install_dependencies()
    setup_env()
    check_mongodb()
    seed_database()
    launch_server()
